-- 코드를 입력하세요
SELECT
    INS.ANIMAL_ID
    , OUTS.ANIMAL_TYPE
    , OUTS.NAME
FROM `ANIMAL_INS` AS `INS`
JOIN `ANIMAL_OUTS` AS `OUTS`
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE 
    SUBSTRING(INS.SEX_UPON_INTAKE, 1, 6) = 'INTACT' 
    AND (OUTS.SEX_UPON_OUTCOME = 'Spayed Female' OR OUTS.SEX_UPON_OUTCOME = 'Neutered Male')
ORDER BY INS.ANIMAL_ID;