-- 코드를 입력하세요
SELECT
    P.MEMBER_NAME	
    , R.REVIEW_TEXT	
    , DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS `REVIEW_DATE`
FROM `REST_REVIEW` AS `R`
JOIN `MEMBER_PROFILE` AS `P`
ON R.MEMBER_ID = P.MEMBER_ID
WHERE R.MEMBER_ID = (
    SELECT `MEMBER_ID`
    FROM `REST_REVIEW` 
    GROUP BY `MEMBER_ID` 
    ORDER BY COUNT(*) DESC
    LIMIT 0, 1
)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;

# SELECT `MEMBER_ID`
# FROM `REST_REVIEW` 
# GROUP BY `MEMBER_ID` 
# ORDER BY COUNT(*) DESC 
# LIMIT 0,1;