-- 코드를 입력하세요
SELECT
    BOOK.BOOK_ID
    , AUTHOR.AUTHOR_NAME
    , CONVERT(BOOK.PUBLISHED_DATE, CHAR) AS `PUBLISHED_DATE`
FROM `BOOK`
JOIN `AUTHOR`
ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE BOOK.CATEGORY = '경제'
ORDER BY BOOK.PUBLISHED_DATE;